### ISSUE TITLE
Doesn't work with sketch 46.2

### ISSUE THREAD

**Issue by frgod** [novemberfiveco/responsivator-sketch-plugin#2]
Hello,

I looking for a such plug-in but it seems to not work with sketch 46.2. When I run .sketchplugin files, nothing happen. I have the same problem on symbol-spacer-sketch-plugin, the problem might be the same.

**Comment by GeertWille** [comment]
Hey @frgod did you fix it now when using the release page to download it from?

**Comment by frgod** [comment]
Hi @GeertWille ! Yes it works. I didn't understand to download the release instead the files on the repository. Thanks you ! and great job :-)
